import type { Category } from './types';

const en: Category[] = [
  {
    id: 'greeting',
    name: '인사 / 기본 예절',
    emoji: '🙏',
    phrases: [
      { id: 'eg1', korean: '안녕하세요',          native: 'Hello',                      pronunciation: '헬로',                        category: 'greeting' },
      { id: 'eg2', korean: '좋은 아침이에요',      native: 'Good morning',               pronunciation: '굿 모닝',                     category: 'greeting' },
      { id: 'eg3', korean: '좋은 저녁이에요',      native: 'Good evening',               pronunciation: '굿 이브닝',                   category: 'greeting' },
      { id: 'eg4', korean: '감사합니다',           native: 'Thank you',                  pronunciation: '땡큐',                        category: 'greeting' },
      { id: 'eg5', korean: '죄송합니다',           native: "I'm sorry",                  pronunciation: '아임 쏘리',                   category: 'greeting' },
      { id: 'eg6', korean: '괜찮아요',             native: "It's okay",                  pronunciation: '잇츠 오케이',                 category: 'greeting' },
      { id: 'eg7', korean: '네',                   native: 'Yes',                        pronunciation: '예스',                        category: 'greeting' },
      { id: 'eg8', korean: '아니요',               native: 'No',                         pronunciation: '노',                          category: 'greeting' },
      { id: 'eg9', korean: '잠깐만요',             native: 'Just a moment, please',      pronunciation: '저스트 어 모먼트 플리즈',     category: 'greeting' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소',
    emoji: '🏨',
    phrases: [
      { id: 'eh1', korean: '체크인 부탁드립니다',          native: "I'd like to check in, please",  pronunciation: '아이드 라이크 투 체크인 플리즈',   category: 'hotel' },
      { id: 'eh2', korean: '체크아웃 부탁드립니다',        native: "I'd like to check out, please", pronunciation: '아이드 라이크 투 체크아웃 플리즈', category: 'hotel' },
      { id: 'eh3', korean: '방 열쇠를 잃어버렸어요',       native: 'I lost my room key',            pronunciation: '아이 로스트 마이 룸 키',           category: 'hotel' },
      { id: 'eh4', korean: '와이파이 비밀번호가 뭔가요?',  native: 'What is the WiFi password?',    pronunciation: '왓 이즈 더 와이파이 패스워드',     category: 'hotel' },
      { id: 'eh5', korean: '수건을 더 주세요',             native: 'Please give me more towels',    pronunciation: '플리즈 기브 미 모어 타월스',       category: 'hotel' },
      { id: 'eh6', korean: '짐을 맡아주실 수 있나요?',     native: 'Can you hold my luggage?',      pronunciation: '캔 유 홀드 마이 러기지',           category: 'hotel' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당 / 음식',
    emoji: '🍽️',
    phrases: [
      { id: 'er1',  korean: '2명입니다',            native: 'Two people, please',        pronunciation: '투 피플 플리즈',                 category: 'restaurant' },
      { id: 'er2',  korean: '4명입니다',            native: 'Four people, please',       pronunciation: '포 피플 플리즈',                 category: 'restaurant' },
      { id: 'er3',  korean: '메뉴 주세요',           native: 'Can I see the menu?',       pronunciation: '캔 아이 씨 더 메뉴',             category: 'restaurant' },
      { id: 'er4',  korean: '이걸로 주세요',         native: "I'll have this, please",    pronunciation: '아일 해브 디스 플리즈',           category: 'restaurant' },
      { id: 'er5',  korean: '추천 메뉴가 뭔가요?',   native: 'What do you recommend?',    pronunciation: '왓 두 유 레커멘드',               category: 'restaurant' },
      { id: 'er6',  korean: '맛있어요!',             native: "It's delicious!",           pronunciation: '잇츠 딜리셔스',                  category: 'restaurant' },
      { id: 'er7',  korean: '계산서 주세요',         native: 'Check, please',             pronunciation: '체크 플리즈',                    category: 'restaurant' },
      { id: 'er8',  korean: '카드 되나요?',          native: 'Do you accept credit cards?', pronunciation: '두 유 억셉트 크레딧 카즈',      category: 'restaurant' },
      { id: 'er9',  korean: '물 주세요',             native: 'Can I have some water?',    pronunciation: '캔 아이 해브 썸 워터',            category: 'restaurant' },
      { id: 'er10', korean: '포장해 주세요',         native: 'Can I get this to go?',     pronunciation: '캔 아이 겟 디스 투 고',           category: 'restaurant' },
      { id: 'er11', korean: '알레르기가 있어요',     native: 'I have a food allergy',     pronunciation: '아이 해브 어 푸드 앨러지',        category: 'restaurant' },
    ],
  },
  {
    id: 'transport',
    name: '교통 / 길 찾기',
    emoji: '🚃',
    phrases: [
      { id: 'et1', korean: '~역은 어디인가요?',  native: 'Where is the ~ station?',  pronunciation: '웨어 이즈 더 ~ 스테이션',  category: 'transport' },
      { id: 'et2', korean: '~에 가고 싶어요',    native: "I'd like to go to ~",      pronunciation: '아이드 라이크 투 고 투 ~', category: 'transport' },
      { id: 'et3', korean: '이 버스 ~에 서나요?', native: 'Does this bus stop at ~?', pronunciation: '더즈 디스 버스 스탑 앳 ~', category: 'transport' },
      { id: 'et4', korean: '택시 불러주세요',    native: 'Please call a taxi',       pronunciation: '플리즈 콜 어 택시',        category: 'transport' },
      { id: 'et5', korean: '여기로 가주세요',    native: 'Please take me here',      pronunciation: '플리즈 테이크 미 히어',    category: 'transport' },
      { id: 'et6', korean: '얼마나 걸리나요?',   native: 'How long will it take?',   pronunciation: '하우 롱 윌 잇 테이크',     category: 'transport' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑',
    emoji: '🛍️',
    phrases: [
      { id: 'es1', korean: '얼마예요?',              native: 'How much is this?',        pronunciation: '하우 머치 이즈 디스',          category: 'shopping' },
      { id: 'es2', korean: '너무 비싸요',             native: "It's too expensive",       pronunciation: '잇츠 투 익스펜시브',           category: 'shopping' },
      { id: 'es3', korean: '이거 입어봐도 되나요?',   native: 'Can I try this on?',       pronunciation: '캔 아이 트라이 디스 온',       category: 'shopping' },
      { id: 'es4', korean: '다른 색상 있나요?',       native: 'Do you have other colors?', pronunciation: '두 유 해브 아더 컬러스',      category: 'shopping' },
      { id: 'es5', korean: '면세 되나요?',            native: 'Is this tax-free?',        pronunciation: '이즈 디스 택스 프리',          category: 'shopping' },
      { id: 'es6', korean: '봉투 주세요',             native: 'Can I have a bag?',        pronunciation: '캔 아이 해브 어 백',           category: 'shopping' },
      { id: 'es7', korean: '카드로 결제할 수 있나요?', native: 'Can I pay by card?',       pronunciation: '캔 아이 페이 바이 카드',       category: 'shopping' },
    ],
  },
  {
    id: 'emergency',
    name: '긴급 / 위급 상황',
    emoji: '🚑',
    phrases: [
      { id: 'ee1', korean: '도와주세요!',              native: 'Help!',                          pronunciation: '헬프',                         category: 'emergency' },
      { id: 'ee2', korean: '경찰을 불러주세요',         native: 'Please call the police',         pronunciation: '플리즈 콜 더 폴리스',           category: 'emergency' },
      { id: 'ee3', korean: '병원에 가야 해요',          native: 'I need to go to the hospital',   pronunciation: '아이 니드 투 고 투 더 하스피틀', category: 'emergency' },
      { id: 'ee4', korean: '여기가 아파요',             native: 'It hurts here',                  pronunciation: '잇 허츠 히어',                 category: 'emergency' },
      { id: 'ee5', korean: '지갑을 잃어버렸어요',       native: 'I lost my wallet',               pronunciation: '아이 로스트 마이 월렛',         category: 'emergency' },
      { id: 'ee6', korean: '한국 대사관이 어디예요?',   native: 'Where is the Korean embassy?',   pronunciation: '웨어 이즈 더 코리안 엠바시',    category: 'emergency' },
    ],
  },
  {
    id: 'communication',
    name: '소통이 안 될 때',
    emoji: '💬',
    phrases: [
      { id: 'ec1', korean: '영어를 못해요',          native: "I don't speak English well", pronunciation: '아이 돈트 스피크 잉글리시 웰', category: 'communication' },
      { id: 'ec2', korean: '한국어 할 수 있나요?',    native: 'Can you speak Korean?',      pronunciation: '캔 유 스피크 코리안',           category: 'communication' },
      { id: 'ec3', korean: '천천히 말해주세요',       native: 'Please speak slowly',        pronunciation: '플리즈 스피크 슬로울리',        category: 'communication' },
      { id: 'ec4', korean: '한 번 더 말해주세요',     native: 'Could you say that again?',  pronunciation: '쿠드 유 세이 댓 어겐',          category: 'communication' },
      { id: 'ec5', korean: '써주실 수 있나요?',       native: 'Could you write it down?',   pronunciation: '쿠드 유 라이트 잇 다운',        category: 'communication' },
    ],
  },
];

export default en;
