import type { Category } from './types';

const zh: Category[] = [
  {
    id: 'greeting',
    name: '인사 / 기본 예절',
    emoji: '🙏',
    phrases: [
      { id: 'zg1', korean: '안녕하세요',      native: '你好',     pronunciation: '니 하오',        category: 'greeting' },
      { id: 'zg2', korean: '좋은 아침이에요', native: '早上好',   pronunciation: '자오 샹 하오',   category: 'greeting' },
      { id: 'zg3', korean: '좋은 저녁이에요', native: '晚上好',   pronunciation: '완 샹 하오',     category: 'greeting' },
      { id: 'zg4', korean: '감사합니다',      native: '谢谢你',   pronunciation: '씨에 씨에 니',   category: 'greeting' },
      { id: 'zg5', korean: '죄송합니다',      native: '对不起',   pronunciation: '뚜이 부 치',     category: 'greeting' },
      { id: 'zg6', korean: '괜찮아요',        native: '没关系',   pronunciation: '메이 관 시',     category: 'greeting' },
      { id: 'zg7', korean: '네',              native: '是的',     pronunciation: '스 더',          category: 'greeting' },
      { id: 'zg8', korean: '아니요',          native: '不是',     pronunciation: '부 스',          category: 'greeting' },
      { id: 'zg9', korean: '잠깐만요',        native: '请稍等',   pronunciation: '칭 샤오 덩',     category: 'greeting' },
    ],
  },
  {
    id: 'hotel',
    name: '숙소',
    emoji: '🏨',
    phrases: [
      { id: 'zh1', korean: '체크인 부탁드립니다',         native: '我要办理入住',       pronunciation: '워 야오 반 리 루 주',             category: 'hotel' },
      { id: 'zh2', korean: '체크아웃 부탁드립니다',       native: '我要退房',           pronunciation: '워 야오 투이 팡',                 category: 'hotel' },
      { id: 'zh3', korean: '방 열쇠를 잃어버렸어요',      native: '我丢了房间钥匙',     pronunciation: '워 띠우 러 팡 지엔 야오 시',      category: 'hotel' },
      { id: 'zh4', korean: '와이파이 비밀번호가 뭔가요?', native: 'WiFi密码是多少？',   pronunciation: '와이파이 미 마 스 뚜오 샤오',     category: 'hotel' },
      { id: 'zh5', korean: '수건을 더 주세요',            native: '请再给我一条毛巾',   pronunciation: '칭 짜이 게이 워 이 티아오 마오 진', category: 'hotel' },
      { id: 'zh6', korean: '짐을 맡아주실 수 있나요?',    native: '可以帮我保管行李吗？', pronunciation: '커 이 방 워 바오 관 싱 리 마',   category: 'hotel' },
    ],
  },
  {
    id: 'restaurant',
    name: '식당 / 음식',
    emoji: '🍜',
    phrases: [
      { id: 'zr1',  korean: '2명입니다',            native: '两个人',           pronunciation: '량 거 런',                    category: 'restaurant' },
      { id: 'zr2',  korean: '4명입니다',            native: '四个人',           pronunciation: '쓰 거 런',                    category: 'restaurant' },
      { id: 'zr3',  korean: '메뉴 주세요',           native: '请给我菜单',       pronunciation: '칭 게이 워 차이 단',           category: 'restaurant' },
      { id: 'zr4',  korean: '이걸로 주세요',         native: '我要这个',         pronunciation: '워 야오 저 거',               category: 'restaurant' },
      { id: 'zr5',  korean: '추천 메뉴가 뭔가요?',   native: '你们有什么推荐菜？', pronunciation: '니 먼 요우 선 머 투이 지엔 차이', category: 'restaurant' },
      { id: 'zr6',  korean: '맛있어요!',             native: '很好吃！',          pronunciation: '헌 하오 츠',                  category: 'restaurant' },
      { id: 'zr7',  korean: '계산서 주세요',         native: '请给我结账',        pronunciation: '칭 게이 워 지에 장',           category: 'restaurant' },
      { id: 'zr8',  korean: '카드 되나요?',          native: '可以刷卡吗？',      pronunciation: '커 이 솨 카 마',               category: 'restaurant' },
      { id: 'zr9',  korean: '물 주세요',             native: '请给我水',          pronunciation: '칭 게이 워 쉐이',              category: 'restaurant' },
      { id: 'zr10', korean: '포장해 주세요',         native: '请打包',            pronunciation: '칭 다 바오',                   category: 'restaurant' },
      { id: 'zr11', korean: '알레르기가 있어요',     native: '我有过敏',          pronunciation: '워 요우 궈 민',                category: 'restaurant' },
    ],
  },
  {
    id: 'transport',
    name: '교통 / 길 찾기',
    emoji: '🚃',
    phrases: [
      { id: 'zt1', korean: '~역은 어디인가요?',   native: '～站在哪里？',     pronunciation: '~ 잔 짜이 나 리',            category: 'transport' },
      { id: 'zt2', korean: '~에 가고 싶어요',     native: '我想去～',          pronunciation: '워 샹 취 ~',                 category: 'transport' },
      { id: 'zt3', korean: '이 버스 ~에 서나요?', native: '这辆车在～停吗？',  pronunciation: '저 량 처 짜이 ~ 팅 마',      category: 'transport' },
      { id: 'zt4', korean: '택시 불러주세요',     native: '请帮我叫出租车',    pronunciation: '칭 방 워 지아오 추 주 처',   category: 'transport' },
      { id: 'zt5', korean: '여기로 가주세요',     native: '请去这里',          pronunciation: '칭 취 저 리',                category: 'transport' },
      { id: 'zt6', korean: '얼마나 걸리나요?',    native: '需要多长时间？',    pronunciation: '쉬 야오 뚜오 창 스 지엔',    category: 'transport' },
    ],
  },
  {
    id: 'shopping',
    name: '쇼핑',
    emoji: '🛍️',
    phrases: [
      { id: 'zs1', korean: '얼마예요?',               native: '多少钱？',         pronunciation: '뚜오 샤오 치엔',              category: 'shopping' },
      { id: 'zs2', korean: '너무 비싸요',              native: '太贵了',           pronunciation: '타이 꾸이 러',                category: 'shopping' },
      { id: 'zs3', korean: '이거 입어봐도 되나요?',    native: '可以试穿吗？',     pronunciation: '커 이 스 촨 마',              category: 'shopping' },
      { id: 'zs4', korean: '다른 색상 있나요?',        native: '有其他颜色吗？',   pronunciation: '요우 치 타 얀 써 마',         category: 'shopping' },
      { id: 'zs5', korean: '면세 되나요?',             native: '可以免税吗？',     pronunciation: '커 이 미엔 쉐이 마',          category: 'shopping' },
      { id: 'zs6', korean: '봉투 주세요',              native: '请给我袋子',       pronunciation: '칭 게이 워 따이 즈',          category: 'shopping' },
      { id: 'zs7', korean: '카드로 결제할 수 있나요?', native: '可以用信用卡付款吗？', pronunciation: '커 이 용 신 용 카 푸 쿠안 마', category: 'shopping' },
    ],
  },
  {
    id: 'emergency',
    name: '긴급 / 위급 상황',
    emoji: '🚑',
    phrases: [
      { id: 'ze1', korean: '도와주세요!',             native: '救命！',           pronunciation: '지우 밍',                    category: 'emergency' },
      { id: 'ze2', korean: '경찰을 불러주세요',        native: '请叫警察',         pronunciation: '칭 지아오 징 차',            category: 'emergency' },
      { id: 'ze3', korean: '병원에 가야 해요',         native: '我需要去医院',     pronunciation: '워 쉬 야오 취 이 위엔',      category: 'emergency' },
      { id: 'ze4', korean: '여기가 아파요',            native: '这里很痛',         pronunciation: '저 리 헌 통',                category: 'emergency' },
      { id: 'ze5', korean: '지갑을 잃어버렸어요',      native: '我丢了钱包',       pronunciation: '워 띠우 러 치엔 바오',        category: 'emergency' },
      { id: 'ze6', korean: '한국 대사관이 어디예요?',  native: '韩国大使馆在哪里？', pronunciation: '한 궈 따 스 관 짜이 나 리', category: 'emergency' },
    ],
  },
  {
    id: 'communication',
    name: '소통이 안 될 때',
    emoji: '💬',
    phrases: [
      { id: 'zc1', korean: '중국어를 못해요',        native: '我不会说中文',     pronunciation: '워 부 후이 솨 중 원',         category: 'communication' },
      { id: 'zc2', korean: '한국어 할 수 있나요?',    native: '你会说韩语吗？',   pronunciation: '니 후이 솨 한 위 마',         category: 'communication' },
      { id: 'zc3', korean: '천천히 말해주세요',       native: '请说慢一点',       pronunciation: '칭 솨 만 이 디엔',            category: 'communication' },
      { id: 'zc4', korean: '한 번 더 말해주세요',     native: '请再说一遍',       pronunciation: '칭 짜이 솨 이 삐엔',          category: 'communication' },
      { id: 'zc5', korean: '써주실 수 있나요?',       native: '可以写下来吗？',   pronunciation: '커 이 씨에 시아 라이 마',     category: 'communication' },
    ],
  },
];

export default zh;
